### ISSUE TITLE
The image manipulation toggle does not appear correctly

### ISSUE THREAD

**Issue by cncoleman** [sul-dlss-deprecated/mirador_sul#1]
See the attached screen shots. These are using mirador.stanford.edu in Chrome (55.0) 
The Icon for image manipulation does eventually resolve.

![screen shot 2017-02-10 at 9 57 49 am](https://cloud.githubusercontent.com/assets/288005/22838046/223ce7dc-ef78-11e6-9dfc-7e06739bc3b5.png)
![screen shot 2017-02-10 at 9 57 39 am](https://cloud.githubusercontent.com/assets/288005/22838052/252162ac-ef78-11e6-93d8-2a441751d3d4.png)

**Comment by cncoleman** [comment]
But the manifest never did appear. You can see the title in the header on the first screen shot. The purl is https://purl.stanford.edu/fn855gk9297?manifest=https://purl.stanford.edu/fn855gk9297/iiif/manifest.json

**Comment by blalbrit** [comment]
@cncoleman which Mirador instance were you addressing above?

**Comment by blalbrit** [comment]
![mirador_sul2](https://cloud.githubusercontent.com/assets/796990/22900119/1b84a300-f1e2-11e6-8d28-489e63cda267.gif)

Having a hard time reproducing this - can you retry?
