### ISSUE TITLE
Add a footer to the home page

### ISSUE THREAD

**Issue by versae** [sul-dlss-deprecated/mirador_sul#100]
It feels always nice to have a footer, at least in the home page, ideally in all views but the workspace one. It could contain the usual suspects: Stanford logo, terms, copyright, etc.

**Comment by mejackreed** [comment]
There are SUL and SU specific footers to be used for web properties. 

See: https://identity.stanford.edu/web-toolkit/

And https://github.com/sul-dlss/SearchWorks/commit/bdd060305d00cca1130ca682303eba3c381a9fc1

Though I think the SUL logo has now changed.
