### ISSUE TITLE
Where do workspaces come from?

### ISSUE THREAD

**Issue by aeschylus** [sul-dlss-deprecated/mirador_sul#17]
Are they:

1. Created "off of" a collection?
2. Duplicated from an existing workspace?
3. Created "new", outside of the context of a collection?

I think there are tradeoffs here. In particular I think 3 creates a number of technical and user communication difficulties, especially when related to the question of what happens when a user adds an object to an open workspace through drag and drop. I think, mostly for technical but also for conceptual/design clarity reasons, that we settled on new workspaces only being able to be created "off of" an existing collection, since objects cannot be removed from the mirador workspace from inside mirador.

**Comment by blalbrit** [comment]
@aeschylus I think 3 is out of scope for May. Though one could start with an empty collection - and the user experience could be smoothed.
