### ISSUE TITLE
Add custom splash screen at mirador.stanford.edu

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss-deprecated/mirador_sul#2]

**Comment by cncoleman** [comment]
![support 001](https://cloud.githubusercontent.com/assets/288005/24264325/4a0e01a0-0fbd-11e7-873c-f493db364a8c.png)
![support 002](https://cloud.githubusercontent.com/assets/288005/24264326/4a0fc256-0fbd-11e7-828f-ac90bcb6f12f.png)

**Comment by cncoleman** [comment]
Prose for the splash page sections. 
[Mirador splash overview.txt](https://github.com/sul-dlss/mirador_sul/files/865793/Mirador.splash.overview.txt)

**Comment by cncoleman** [comment]
The animated gifs I'm creating now. Though I'm not sure what to do for "Share". I'm not quite sure how that is going to work. The functionality that I am highlighting there is simply the bookmarking of a workspace and the ability to share that with others. I have not seen that action in practice. I'm imagining how it works.  The animated gifs will be about 800 x 550. If there is a particular spec for those images, please let me know.

**Comment by mejackreed** [comment]
This is great Nicole.. thanks for putting this up.

**Comment by cncoleman** [comment]
A placeholder video file is here: https://github.com/sul-dlss/mirador_sul/tree/gh-pages/public/media
I'll make a more 'finished' video with alternate formats.

**Comment by csbailey5t** [comment]
@cncoleman Do you have finished gifs for the below the fold sections?

**Comment by cncoleman** [comment]
![discover2](https://cloud.githubusercontent.com/assets/288005/24921140/a727d10a-1e9e-11e7-9d37-291fb221516f.gif)
![discover_notext](https://cloud.githubusercontent.com/assets/288005/24921295/2ef092fc-1e9f-11e7-84d1-81d83d72c37f.gif)

**Comment by blalbrit** [comment]
@cncoleman - can you clarify what these gifs are supposed to be?

**Comment by cncoleman** [comment]
This is the first gif for "Discover".

**Comment by cncoleman** [comment]
I will title each gif with the corresponding section specified in the text file.

**Comment by cncoleman** [comment]
![compare](https://cloud.githubusercontent.com/assets/288005/24923441/63564d5a-1ea6-11e7-825a-2a3273b778b5.gif)

**Comment by cncoleman** [comment]
640 x 427

![compare640](https://cloud.githubusercontent.com/assets/288005/24924470/c432b232-1ea9-11e7-9f5c-2e7566b3f754.gif)
![discover640](https://cloud.githubusercontent.com/assets/288005/24924471/c4555210-1ea9-11e7-9c53-30ed5e615615.gif)

**Comment by cncoleman** [comment]
![zoom](https://cloud.githubusercontent.com/assets/288005/24934112/93a577d8-1ece-11e7-83e5-94959007b117.gif)

**Comment by cncoleman** [comment]
![annotate](https://cloud.githubusercontent.com/assets/288005/24935438/f4c11db2-1ed6-11e7-8604-12e26ea41f08.gif)
