### ISSUE TITLE
Create a mirador instance view

### ISSUE THREAD

**Issue by jkeck** [sul-dlss-deprecated/mirador_sul#20]
This will be a thin wrapper around the mirador instance/markup.

- [ ] Needs to dereference hash identifier and fetch state from the database (to instantiate mirador)
- [ ] Adding manifest via DnD needs to update the collection.
- [ ] Identify annotation endpoint

**Comment by aeschylus** [comment]
https://github.com/ProjectMirador/mirador/wiki/Configuration-Guides#adding-buttons-to-the-menu-bar
