### ISSUE TITLE
Remove workspace belonging to collection

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss-deprecated/mirador_sul#26]

**Comment by jkeck** [comment]
@cncoleman & @blalbrit now that we've decided that collections + workspaces aren't tied to each other (e.g. for syncing complications) will there still be desire to indicate which collection a workspace was instantiated from? (even though it might not represent the state the mirador instance was instantiated from)

**Comment by blalbrit** [comment]
@jkeck - I think for now we could indicate to a user to name a workspace with some meaningful title - could we seed that title with the collection it originated in?

**Comment by jkeck** [comment]
We can do _almost_ anything™

**Comment by blalbrit** [comment]
That's great! Then yes - let's seed the workspace title from the collection for now, allowing the user to modify that with additional description.
