### ISSUE TITLE
Add login and user accounts (Stanford only) for mirador.stanford.edu

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss-deprecated/mirador_sul#4]

**Comment by csbailey5t** [comment]
@blalbrit For the MVP, do we need both Stanford and local to the app (for folks at the symposium not from Stanford)? Can we get by with just local and add Stanford at a later point?

**Comment by blalbrit** [comment]
@csbailey5t For MVP we can get by with local and add Stanford later.
